name = "MOGMOG"
uuid = "463befc3-bf57-4ff5-887d-5b8e2621417b"
authors = ["Adam <adamgoast360@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"

[compat]
NNlib = "0.9.30"
julia = "1.10"
